default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: craft_game_app_development
  username: postgres
  password: "11321"

test:
  <<: *default
  database: craft_game_app_test
  username: postgres
  password: "11321"

production:
  <<: *default
  database: craft_game_app_production
  username: craft_game_app
  password: <%= ENV["CRAFT_GAME_APP_DATABASE_PASSWORD"] %>
